#define DEBUG_STR_SERVER_INIT "SERVER INIT"
#define DEBUG_STR_CLIENT_INIT "CLIENT INIT"
#define DEBUG_STR_SERVER_SIDE "SERVER"
#define DEBUG_STR_CLIENT_SIDE "CLIENT"
#define DEBUG_STR_NPC_INIT "NPC INIT"
#define DEBUG_STR_EVENT "EVENT"
#define DEBUG_STR_PLAYER_ACTION "PLAYER ACTION"
#define DEBUG_STR_INTEL "INTEL"

#define INSURGENT_CLASS "cfp_o_is_base"
#define INTEL_ITEMS_WHITELIST ["CUP_item_Kostey_photos", "CUP_item_Cobalt_File", "CUP_item_Kostey_notebook", "CUP_item_Moscow_Bombing_File"];

#define KEY_PLAYER_PROFILES "dpl_player_profiles"
#define KEY_PLAYER_LOGGEDIN "dpl_is_logged_in"
#define KEY_INTEL_PROGRESS "dpl_intel_progess"
#define KEY_REGISTERED "dpl_registered"

#define KEY_REPUTATION "dpl_profile_reputation"
#define KEY_MONEY "dpl_profile_money"
#define KEY_CLASS "dpl_profile_class"
#define KEY_NAME "dpl_profile_name"
#define KEY_UID "dpl_profile_uid"
#define KEY_IS_RENEGADE "dpl_profile_renegade"
#define KEY_PRISON_START "dpl_profile_prison_start"
#define KEY_POSITION "dpl_profile_position"
