#define DEBUG_STR_SERVER_INIT "SERVER INIT"
#define DEBUG_STR_CLIENT_INIT "CLIENT INIT"
#define DEBUG_STR_NPC_INIT "NPC INIT"
#define DEBUG_STR_EVENT "EVENT"
#define DEBUG_STR_PLAYER_ACTION "PLAYER ACTION"

define REP_PER_DOGTAG 5
