class CfgFunctions {
    class coopr {
        class coopr_persistence_local {
            file = "x\coopr\addons\persistence\local";
            class extDB3sql {};
            class getCharactersIDLocal {};
            class updateCharacterLocal {};
            class initPlayerPersistenceLocal {};
            class hasPlayerLocal {};
            class initPersistenceLocal {};
            class getCharactersLocal {};
            class getAllCharactersLocal {};
            class createCharacterLocal{};
            class removeCharacterLocal {};
            class localDatabaseRefresh {};
            class saveTaskLocal {};
            class getTaskLocal {};
            class getTaskCountLocal {};
            class initServerMetaLocal {};
            class pushTaskQueueLocal {};
            class getAllQueuedTasksLocal {};
            class getQueuedTasksCountLocal {};
            class popQueuedTaskLocal {};
            class deleteQueuedTaskLocal {};
            class initReconReportLocal {};
            class getReportIdForCharacterLocal {};
            class saveReconEntryLocal {};
            class getEntriesForReportLocal {};
        }
        class coopr_persistence_functions {
            file = "x\coopr\addons\persistence\functions";
            class setupPersistenceModule {};
            class updateCharacterSlots {};
            class createCharacter {};
            class updateState {};
            class serializeCoopR {};
            class deserializeCoopR {};
            class getNewCharacterState {};
            class getAllCharacters {};
            class characterStatePrettyLog {};
            class sync {};
            class syncPlayers {};
            class removeCharacter {};
            class initPersistence {};
            class hasPlayer {};
            class initPlayerPersistence {};
            class updateCharacter {};
            class getCharactersID {};
            class getCharacters {};
            class saveTask {};
            class getTask {};
            class getTaskCount {};
            class initServerMeta {};
            class pushTaskQueue {};
            class getAllQueuedTasks {};
            class getQueuedTasksCount {};
            class popQueuedTask {};
            class deleteQueuedTask {};
            class initReconReport {};
            class getReportIdForCharacter {};
            class saveReconEntry {};
            class getEntriesForReport {};
        }
    }
}
