// This .hpp file is created to have one source of truth for all UI IDs
// makes it easier to have an overview and make changes

// LOGIN
#define GUI_ID_LOGIN_DIALOG 1101
#define GUI_ID_LOGIN_DIALOG_BACKGROUND  1000
#define GUI_ID_LOGIN_DIALOG_PROFILE_1  1200
#define GUI_ID_LOGIN_DIALOG_PROFILE_1_OVERLAY  1210
#define GUI_ID_LOGIN_DIALOG_PROFILE_2  1201
#define GUI_ID_LOGIN_DIALOG_PROFILE_2_OVERLAY  1220
#define GUI_ID_LOGIN_DIALOG_PROFILE_3  1202
#define GUI_ID_LOGIN_DIALOG_PROFILE_3_OVERLAY  1230
#define GUI_ID_LOGIN_DIALOG_PROFILE_1_BUTTON  1600
#define GUI_ID_LOGIN_DIALOG_PROFILE_2_BUTTON  1601
#define GUI_ID_LOGIN_DIALOG_PROFILE_3_BUTTON  1602
#define GUI_ID_LOGIN_DIALOG_PROFILE_1_LABEL  1001
#define GUI_ID_LOGIN_DIALOG_PROFILE_1_INFO  1100
#define GUI_ID_LOGIN_DIALOG_PROFILE_2_INFO  1101
#define GUI_ID_LOGIN_DIALOG_PROFILE_3_INFO  1102

// ARMORY
#define GUI_ID_ARMORY_DIALOG 1102
#define GUI_ID_ARMORY_BACKGROUND: RSCTEXT idc 2000
#define GUI_ID_ARMORY_LISTBOX: RSCLISTBOX idc 2500
#define GUI_ID_ARMORY_INFO_TEXTBOX: RSCSTRUCTUREDTEXT idc 2001
#define GUI_ID_ARMORY_REPUTATION_TEXTBOX: RSCTEXT idc 2002
#define GUI_ID_ARMORY_BUTTON_EQUIP: RSCBUTTON idc 2600

// CHARACTER
#define GUI_ID_CHARACTER_CREATION_DIALOG 1103
#define GUI_ID_CHARACTER_BACKGROUND idc 3000
#define GUI_ID_CHARACTER_TITLE idc 3001
#define GUI_ID_CHARACTER_INFO idc 3003
#define GUI_ID_CHARACTER_BUTTON_CREATE idc 3600
#define GUI_ID_CHARACTER_EDIT_NAME idc 3400
#define GUI_ID_CHARACTER_LABEL_NAME idc 3002
#define GUI_ID_CHARACTER_LABEL_SPECIALISATION idc 3003
#define GUI_ID_CHARACTER_COMBO_ROLE idc 3100
#define GUI_ID_CHARACTER_CLASSPICTURE idc 3200

// SUPPLY
#define GUI_ID_SUPPLY_DIALOG 1104
#define GUI_ID_SUPPLY_BACKGROUND 11040
#define GUI_ID_SUPPLY_AMMO_TEXTBOX 11041
#define GUI_ID_SUPPLY_EQUIPMENT_TEXTBOX 11042
#define GUI_ID_SUPPLY_AMMO_EDIT 11043
#define GUI_ID_SUPPLY_EQUIPMENT_EDIT 11044
#define GUI_ID_SUPPLY_REQUEST_BUTTON 11045

// RECONREPORT
#define GUI_ID_RECONREPORT_DIALOG 1105
#define GUI_ID_RECONREPORT_BACKGROUND 11050
#define GUI_ID_RECONREPORT_MARKER_EDIT 11054
#define GUI_ID_RECONREPORT_TYPE_COMBO 11051
#define GUI_ID_RECONREPORT_STRENGTH_COMBO 11052
#define GUI_ID_RECONREPORT_BEHAVIOUR_COMBO 11053
#define GUI_ID_RECONREPORT_SENDER_LABEL 11059
#define GUI_ID_RECONREPORT_WRITE_BUTTON 11056
#define GUI_ID_RECONREPORT_REMOVE_BUTTON 11058
#define GUI_ID_RECONREPORT_TIME_LABEL 110510
#define GUI_ID_RECONREPORTS_ENTRIES_STRUCT 11055
#define GUI_ID_RECONREPORT_ENTRYREMOVE_COMBO 11057

#define GUI_ID_TASKBOARD_DIALOG 1106
