// This .hpp file is created to have one source of truth for all UI IDs
// makes it easier to have an overview and make changes

// LOGIN
#define GUI_ID_LOGIN_DIALOG 1000
#define GUI_ID_LOGIN_CHARACTER_LIST 1200

#define GUI_ID_LOGIN_CHARACTER_CREATION 1300
#define GUI_ID_LOGIN_CHARACTER_CREATION_CREATE 1301
#define GUI_ID_LOGIN_CHARACTER_CREATION_NAME_INPUT 1302
#define GUI_ID_LOGIN_CHARACTER_CREATION_ROLE_COMBO 1303
#define GUI_ID_LOGIN_CHARACTER_CREATION_ERROR 1304
#define GUI_ID_LOGIN_CHARACTER_CREATION_ROLE_PICTURE 1305

#define GUI_ID_LOGIN_CHARACTER_DETAILS 1400
#define GUI_ID_LOGIN_CHARACTER_DETAILS_DELETE_BUTTON 1401
#define GUI_ID_LOGIN_CHARACTER_DETAILS_PLAY_BUTTON 1402
#define GUI_ID_LOGIN_CHARACTER_DETAILS_ROLE 1403
#define GUI_ID_LOGIN_CHARACTER_DETAILS_PERKS 1404
#define GUI_ID_LOGIN_CHARACTER_DETAILS_TRAITS 1405
#define GUI_ID_LOGIN_CHARACTER_DETAILS_TEXT 1406
#define GUI_ID_LOGIN_CHARACTER_DETAILS_TITLE 1407

#define GUI_ID_LOGIN_CHARACTER_ROLE_DESCRIPTION 1500
#define GUI_ID_LOGIN_CHARACTER_ROLE_DESCRIPTION_TEXT 1501

// ARMORY
#define GUI_ID_ARMORY_DIALOG 2000
#define GUI_ID_ARMORY_BACKGROUND 2001
#define GUI_ID_ARMORY_LISTBOX 2002
#define GUI_ID_ARMORY_INFO_TEXTBOX 2003
#define GUI_ID_ARMORY_REPUTATION_TEXTBOX 2004
#define GUI_ID_ARMORY_BUTTON_EQUIP 2005

// CHARACTER
#define GUI_ID_CHARACTER_CREATION_DIALOG 3000
#define GUI_ID_CHARACTER_BACKGROUND 3001
#define GUI_ID_CHARACTER_TITLE 3002
#define GUI_ID_CHARACTER_INFO 3004
#define GUI_ID_CHARACTER_BUTTON_CREATE 3005
#define GUI_ID_CHARACTER_EDIT_NAME 3006
#define GUI_ID_CHARACTER_LABEL_NAME 3007
#define GUI_ID_CHARACTER_LABEL_SPECIALISATION 3008
#define GUI_ID_CHARACTER_COMBO_ROLE 3009
#define GUI_ID_CHARACTER_CLASSPICTURE 3010

// SUPPLY
#define GUI_ID_SUPPLY_DIALOG 4000
#define GUI_ID_SUPPLY_BACKGROUND 4001
#define GUI_ID_SUPPLY_AMMO_TEXTBOX 4002
#define GUI_ID_SUPPLY_EQUIPMENT_TEXTBOX 4003
#define GUI_ID_SUPPLY_AMMO_EDIT 4004
#define GUI_ID_SUPPLY_EQUIPMENT_EDIT 4005
#define GUI_ID_SUPPLY_REQUEST_BUTTON 4006

// RECON_REPORT
#define GUI_ID_RECON_REPORT_DIALOG 5000
#define GUI_ID_RECON_REPORT_BACKGROUND 5001
#define GUI_ID_RECON_REPORT_MARKER_EDIT 5002
#define GUI_ID_RECON_REPORT_TYPE_COMBO 5003
#define GUI_ID_RECON_REPORT_STRENGTH_COMBO 5004
#define GUI_ID_RECON_REPORT_BEHAVIOUR_COMBO 5005
#define GUI_ID_RECON_REPORT_SENDER_LABEL 5006
#define GUI_ID_RECON_REPORT_WRITE_BUTTON 5007
#define GUI_ID_RECON_REPORT_REMOVE_BUTTON 5008
#define GUI_ID_RECON_REPORT_TIME_LABEL 5009
#define GUI_ID_RECON_REPORTS_ENTRIES_STRUCT 5010
#define GUI_ID_RECON_REPORT_ENTRYREMOVE_COMBO 5011

// MISSION_BOARD
#define GUI_ID_MISSIONBOARD_DIALOG 6000
#define GUI_ID_MISSIONBOARD_BACKGROUND 6001
#define GUI_ID_MISSIONBOARD_DOCUMENT_COMBAT 6002
#define GUI_ID_MISSIONBOARD_DOCUMENT_RECON 6003
#define GUI_ID_MISSIONBOARD_MISSION_1 6004
#define GUI_ID_MISSIONBOARD_MISSION_2 6005
#define GUI_ID_MISSIONBOARD_MISSION_3 6006
#define GUI_ID_MISSIONBOARD_MISSION_1_TYPE_LABEL 6007
#define GUI_ID_MISSIONBOARD_MISSION_2_TYPE_LABEL 6008
#define GUI_ID_MISSIONBOARD_MISSION_3_TYPE_LABEL 6009
#define GUI_ID_MISSIONBOARD_MISSION_1_ACCURACY 6010
#define GUI_ID_MISSIONBOARD_MISSION_2_ACCURACY 6011
#define GUI_ID_MISSIONBOARD_MISSION_3_ACCURACY 6012

