#include "..\script_component.hpp"

#define COOPR_TIMER_MISSION_ROUTINE 5
#define COOPR_TIMER_RECON_ROUTINE 5
#define COOPR_TIMER_DESERTION_ROUTINE 5
#define COOPR_TIMER_MISSION_FRESHNESS_ROUTINE 120
