waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};
SLOG("static data called");
ALIVE_autoGeneratedTasks = ["MilAssault",
                            "CivAssault",
                            "Assassination",
                            "DestroyVehicles",
                            "DestroyInfantry",
                            "SabotageBuilding",
                            "InsurgencyPatrol",
                            "InsurgencyDestroyAssets",
                            "Rescue",
                            "CSAR"];

